### ISSUE TITLE
how to use your project in andriod studio

### ISSUE THREAD

**Issue by cstangga** [hernanhawryluk/instagram-clone-app#1]
Hi
i clone your project and excute 
1. USB debugger mode activated
2. i have troubleshooting : This computer is not authorized for developing on Device R3CTC045E2J.

how to solve this troubleshooting

**Comment by hernanhawryluk** [comment]
Hello! I’ve updated the dependencies and resolved a few issues that arose from the update. With Expo v51, you should now be able to run the project smoothly. I’ve also added instructions on the main page for your reference.
